### ISSUE TITLE
Setup YEW for frontend development

### ISSUE THREAD

**Issue by iDeniyi** [AlbertaSat/ex3_ground_station#5]
- initialize a simple YEW project template
- add pages for different purposes such as sending commands, command history, list of commands, etc.
- create a navbar and router to navigate between the different pages.

**Comment by dheadrick1618** [comment]
Please attach your current branch to this issue @iDeniyi . Thanks! Great work. I think this is a great start to our ground station site, so we can have something clean and nice to use for the operators to communicate with the satellite not restricted to a command line  :D
